### ISSUE TITLE
Calico, Flannel, Coredns 安装方法

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#164]
**What would you like to be added**:

**Why is this needed**:

**Comment by magicsong** [comment]
flannel hostgw安装方式:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan" ##这里改成host-gw
      }
    }
```

找到上面的`Type`，其值改为host-gw
