### ISSUE TITLE
[Ray] Node 节点自动增加和删除

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#49]
Node 节点自动根据负载（CPU、内存使用率）进行弹性伸缩，当 Node 节点资源达到指定阈值时，自动添加 Node 节点到 K8S 集群。

**Comment by wnxn** [comment]
1. CPU 和 内存使用率 指标从何处获取？
从 k8s node 资源对象 status 获取可行么？ @benjaminhuo 
```
  allocatable:
    cpu: "8"
    ephemeral-storage: "190120262547"
    hugepages-2Mi: "0"
    memory: 16329236Ki
    pods: "120"
  capacity:
    cpu: "8"
    ephemeral-storage: 206293688Ki
    hugepages-2Mi: "0"
    memory: 16431636Ki
    pods: "120"
```
2. 如何调用相应的 APPCenter 的 API ？ @zheng1 
3. 实现方式。
建议在 k8s 集群内启动一个 Go 程序 Pod 实现自动扩缩。
4. 缩 Node 默认不打开，可提供设置项供设置。
5. 应提供扩缩阈值。Node 达到多少负载时扩集群，缩集群。
6. 建议增加 Pod 个数指标触发 Node 节点自动增加和删除。
